### ISSUE TITLE
ständiger Adapter Neustart bei Nichterreichbarkeit

### ISSUE THREAD

**Issue by thatso** [foxthefox/ioBroker.musiccast#39]
Musiccast Adapter: 0.1.3
JS controller: 3.0.18
Node.js: 10.20.1
NPM: 6.14.4

Wenn ein Endgerät nicht erreichbar ist, startet der Adapter pausenlos neu.
Beispiel:

host.iobroker	2020-04-25 12:11:40.974	info	Restart adapter system.adapter.musiccast.0 because enabled
host.iobroker	2020-04-25 12:11:40.974	info	instance system.adapter.musiccast.0 terminated with code 0 (NO_ERROR)
musiccast.0	2020-04-25 12:11:40.450	info	(10096) Terminated (NO_ERROR): Without reason
musiccast.0	2020-04-25 12:11:40.449	info	(10096) terminating
musiccast.0	2020-04-25 12:11:40.448	error	(10096) Error: connect EHOSTUNREACH x.x.x.x:80 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
musiccast.0	2020-04-25 12:11:40.448	error	(10096) uncaught exception: connect EHOSTUNREACH x.x.x.x:80
musiccast.0	2020-04-25 12:11:40.447	error	(10096) Error: connect EHOSTUNREACH x.x.x.x:80 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
musiccast.0	2020-04-25 12:11:40.447	error	(10096) uncaught exception: connect EHOSTUNREACH x.x.x.x:80
musiccast.0	2020-04-25 12:11:40.445	error	(10096) Error: connect EHOSTUNREACH x.x.x.x:80 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
musiccast.0	2020-04-25 12:11:40.444	error	(10096) uncaught exception: connect EHOSTUNREACH x.x.x.x:80
musiccast.0	2020-04-25 12:11:40.444	error	(10096) Error: connect EHOSTUNREACH x.x.x.x:80 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
musiccast.0	2020-04-25 12:11:40.444	error	(10096) uncaught exception: connect EHOSTUNREACH x.x.x.x:80
musiccast.0	2020-04-25 12:11:40.444	error	(10096) Error: connect EHOSTUNREACH x.x.x.x:80 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
musiccast.0	2020-04-25 12:11:40.444	error	(10096) uncaught exception: connect EHOSTUNREACH x.x.x.x:80
musiccast.0	2020-04-25 12:11:40.443	error	(10096) Error: connect EHOSTUNREACH x.x.x.x:80 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
musiccast.0	2020-04-25 12:11:40.443	error	(10096) uncaught exception: connect EHOSTUNREACH x.x.x.x:80
musiccast.0	2020-04-25 12:11:40.442	info	(10096) cleaned everything up...
musiccast.0	2020-04-25 12:11:40.441	error	(10096) Error: connect EHOSTUNREACH x.x.x.x:80 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1107:14)
musiccast.0	2020-04-25 12:11:40.440	error	(10096) uncaught exception: connect EHOSTUNREACH x.x.x.x:80

**Comment by foxthefox** [comment]
muss ich bei mir mal reproduzieren

**Comment by manoloxxl** [comment]
Kann ich bestätigen. Receiver hängt an einer geschalteten Steckdose und das führt zu Dauerneustarts.

**Comment by Scrounger** [comment]
@foxthefox 
fix in pr #41 

Das Problem tritt erst ab js-controller >=3.x auf.
Ich hab das mal quick and dirty behoben. Das Kernproblem liegt aber in deiner lib, hier solltest du noch ein sauberes Error handling einbauen und die ganzen promise funktionen mit .catch() versehen, z.B hier
https://github.com/foxthefox/yamaha-yxc-nodejs/blob/422038460ad6d19e28ce325da612dac0985ce8a4/yxc_api_cmd.js#L10

https://github.com/foxthefox/yamaha-yxc-nodejs/blob/422038460ad6d19e28ce325da612dac0985ce8a4/yxc_api_cmd.js#L33

https://github.com/foxthefox/yamaha-yxc-nodejs/blob/422038460ad6d19e28ce325da612dac0985ce8a4/yxc_api_cmd.js#L54

**Comment by foxthefox** [comment]
Viele Dank für den PR. Ich habe derzeitig kaum Zeit für die Adapterentwicklung.
